name : Continous Deployment pipeline

# ssh into vm and then uploading the code and then restarting the vm

on:
  push:
    branches
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup node js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      
      - name: ssh connection with the vm
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/azureuser/wanderconnect/backend
            git pull origin main
            npm install
            pm2 restart 0